infinite:
  gateway:
    name: api-gateway
    port: 10011
    evn: dev
    configCenter:
      address: 127.0.0.1:8848
      enabled: true
      type: nacos
      nacosConfig:
        namespace: Public
        dataId: Infinite-Gateway
        group: DEFAULT_GROUP
        timeout: 5000
    registerCenter:
      type: nacos
      address: 127.0.0.1:8848
      nacosConfig:
        namespace: Public
        dataId: Infinite-Gateway
        group: DEFAULT_GROUP
        timeout: 5000
logging:
  level:
    root: error